name: Push to Fork (kryptosphere-dev)

on:
  push:
    branches:
      - main

jobs:
  sync-to-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set Git config
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: Make change (example)
        run: |
          echo "Last pushed at $(date -u)" > version.txt
          git add version.txt

      - name: Remove workflows from commit
        run: |
          git restore --staged .github/workflows || true
          git restore .github/workflows || true

      - name: Commit if needed
        run: |
          git diff --cached --quiet || git commit -m "Update version file at $(date -u)"

      - name: Push to kryptosphere-dev
        run: |
          git remote add fork git@github.com:kryptosphere-dev/kryptosphere-website.git
          git push fork main
